#!/usr/bin/env python3
"""Create compact public-policy facts and exact source membership; metadata only."""
import csv,datetime,hashlib,json,re,subprocess
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];P=ROOT/'sleep_unified_research_v4';S=P/'source_provenance';V=P/'reviews'
NOW=datetime.datetime.now(datetime.timezone.utc).isoformat()
def sha(p):
 h=hashlib.sha256()
 with Path(p).open('rb') as f:
  for x in iter(lambda:f.read(65536),b''):h.update(x)
 return h.hexdigest()
def save(p,v):
 with p.open('x') as f:json.dump(v,f,indent=2);f.write('\n')
def table(p,rows):
 with p.open('x',newline='') as f:
  w=csv.DictWriter(f,fieldnames=list(rows[0]),delimiter='\t');w.writeheader();w.writerows(rows)
core_path=P/'reviews/independent_core_pipeline_replay_manifest_v4.json';ext_path=P/'manifests/extension_raw_acquisition_plan_v4_8.json';val_path=P/'statistical_validation/validation_raw_replay_design_v1.json';reg_path=ROOT/'config/public_gwas_sources.tsv';sleep_path=S/'sleep_clinician_finngen_R13_insomnia_HEAD_v4.json'
core=json.loads(core_path.read_text());ext=json.loads(ext_path.read_text());val=json.loads(val_path.read_text());sleep=json.loads(sleep_path.read_text())
reg={r['source_id']:r for r in csv.DictReader(reg_path.open(),delimiter='\t')}
receipts=[S/'source_policy_microfetch_receipt_v4_2.json',S/'source_policy_followup_microfetch_receipt_v4_1.json',S/'source_policy_followup_microfetch_receipt_v4_2.json']
responses={r['id']:r for p in receipts for r in json.loads(p.read_text())['responses']}
for r in responses.values():assert sha(r['path'])==r['sha256']
assert len(core['rows'])==45 and len(ext['members'])==100 and len(val['members'])==13
assert sha(S/'source_rights_evidence_gaps_v4.tsv')=='e218575e8ffc66e26b9a16ef9d43e7b7a830c66a01839c2491386e2a68b2b31e'
fg_plan_path=P/'manifests/finngen_preprocessing_plan_v4_3_2.json'
fg_plan=json.loads(fg_plan_path.read_text());assert fg_plan['source_generation']=='1777989563097164'
inputs=[fg_plan_path,core_path,ext_path,val_path,reg_path,sleep_path,S/'sleep_clinician_finngen_R13_manifest_selection_v4.json',S/'source_rights_evidence_gaps_v4.tsv',ROOT/'discovery_extension/sleep_submission_evidence_v1/16_PUBLIC_RELEASE_AND_LICENSE_AUDIT.md',ROOT/'sleep_unified_research_v1/reviews/provenance_v1_source_admissibility.tsv',P/'manifests/validation_raw_acquisition_plan_v4_3.json',P/'reviews/validation13_acquisition_independent_review_seal_v3.json']+receipts
before={str(p):sha(p) for p in inputs}
CATALOG='https://www.ebi.ac.uk/gwas/docs/faq/';EBI='https://www.ebi.ac.uk/about/terms-of-use/'
POLICIES=[]
def fact(id,group,url,mode,access,reuse,cite,gap,evidence=''):
 POLICIES.append(dict(policy_id=id,source_group=group,official_url=url,observed_utc=NOW,verification_mode=mode,access_and_use_fact=access,redistribution_fact=reuse,citation_fact=cite,precise_remaining_gap=gap,evidence_binding=evidence))
def response_binding(id):
 r=responses[id];return r['url']+' | response_SHA256='+r['sha256']+' | HTTP='+r['http_code']+' | '+r['retrieved_utc']
fact('PAN_UKB','Pan-UKB','https://pan.ukbb.broadinstitute.org/downloads/index.html','LIVE_OFFICIAL_WEB_TEXT','Free download; derived-result publication encouraged; UK Biobank terms and no reidentification apply.','GWAS results explicitly CC BY 4.0; license grant is source-specific.','Acknowledge Pan-UKB and UK Biobank; cite Karczewski/Gupta/Kanai2025 DOI10.1038/s41588-025-02335-7.','Human verifies attribution, UKB/institutional conditions and proposed publication contents; this review does not authorize raw hosting.')
fact('CATALOG_DEFAULT','GWAS Catalog',CATALOG,'LIVE_OFFICIAL_WEB_TEXT','Public summary statistics; exact accession terms and adjacent READMEs can be exceptions.','Generic CC0 statement explicitly excepts individual study/download terms.','Cite original study, accession, Catalog and access/download date.','Never replace accession exceptions with generic CC0. FAQ says new-submission policy began March2021; methods page says2022, so upload date is not a license decision.')
fact('EBI_OWNER_TERMS','EMBL-EBI',EBI,'LIVE_OFFICIAL_WEB_TEXT','EBI adds no restriction beyond original-owner terms; revised2024-02-05.','Owners retain rights; users must respect third-party rights; additional resource-specific terms can prevail.','Resource/source attribution expected.','For EBI-term accessions, human must reconcile applicable owner/readme conditions before raw redistribution; no blanket sublicense is inferred.')
fact('FINNGEN_R9','FinnGen R9','https://finngen.gitbook.io/documentation/r9/data-download','LIVE_OFFICIAL_WEB_TEXT','R9 documentation routes summary-statistics access through a form and emailed instructions.','No explicit raw redistribution license found in this inspected instruction page.','Acknowledge FinnGen participants/investigators; cite Kurki2023 DOI10.1038/s41586-022-05473-8.','Human supplies applicable registration/terms record and confirms downstream release conditions; no form submitted.')
fact('FINNGEN_R13','FinnGen R13','https://finngen.gitbook.io/documentation/data-download','LIVE_OFFICIAL_WEB_TEXT','Current public instructions route access through registration; official site dates DF13 release2026-06-02 and free Cloud access.','Free access and citation language do not establish a raw redistribution grant.','Acknowledge FinnGen; cite Kurki2023; keyword requested where possible.','Confirm applicable registration/terms and derivative/raw publication scope; applies to eleven validation endpoints plus F5_INSOMNIA.')
fact('FINNGEN_FORM','FinnGen form','https://elomake.helsinki.fi/lomakkeet/124935/lomake.html','LIVE_OFFICIAL_WEB_TEXT','Form requires agreement against identifying individuals and compliance with laws/institutional human-subjects and genetics policies.','No separate redistribution grant observed in rendered form.','FinnGen acknowledgment requested.','Human confirms applicable agreement/registration record; no authorization or compliance status invented.')
fact('SDKP','Sleep Portal','https://kp4cd.org/policies/sleep','LIVE_OFFICIAL_WEB_TEXT','Research use of analysis results permitted; bulk download only for publicly offered datasets; no participant identification/contact and confidentiality conditions.','No blanket underlying GWAS redistribution license observed.','Cite portal, dataset publication and dated URL; RRID:SCR_016611.','Human confirms underlying file-owner terms; portal permission to analyze is not a raw-file sublicense.')
fact('CNCR_JANSEN','CNCR Jansen2019','https://cncr.nl/research/summary_statistics/','LIVE_OFFICIAL_WEB_TEXT','Page licenses listed work CC BY-NC-SA4.0; forbids identification/stigmatizing projects; commercial use requires permission. Jansen2019 listed download excludes23andMe.','Observed noncommercial/share-alike license and additional conditions; no unrestricted or full23andMe grant.','Cite Jansen2019 DOI10.1038/s41588-018-0333-3.','Human confirms exact frozen UKB-only file applicability and research/noncommercial/attribution/adaptation compliance before release; do not contact or replace source.')
fact('PGC_TERMS','PGC','https://pgc.unc.edu/for-researchers/download-results/','LIVE_OFFICIAL_WEB_TEXT','Scientific research use; commercial/for-profit permission required; no identification; institutional/genetics compliance.','Cross-posting/making data available elsewhere prohibited by official page.','Cite relevant PGC studies; prepublication priorities also specified.','Public Figshare license fields conflict with these restrictions; human must resolve governing source conditions, without this review selecting permissive terms.')
fact('PGC_FIGSHARE','Exact PGC versions','https://api.figshare.com/v2/articles/19426775/versions/7','LIVE_HTTP200_METADATA','Exact scz2022v7,bip2021v2,adhd2022v1 API records identify original registered file IDs and sizes.','All three record license fields say CC BY4.0; retain alongside PGC conditions.','Exact DOI/version and original papers.','Human resolves conflict before reposting; README policies remain material.', ' | '.join(response_binding(x) for x in ['figshare_scz_v7','figshare_bipolar_v2','figshare_adhd_v1']))
fact('PGC_READMES','PGC release READMEs','https://ndownloader.figshare.com/files/40036699','LIVE_HTTP200_POLICY_PDF_TEXT','ADHD README permits scientific/educational use and collaborator sharing; SCZ README invokes general PGC conditions and published-study priority.','ADHD explicitly prohibits public redistribution/reposting; SCZ incorporates generic PGC conditions.','Source publications required.','The restrictive release documentation does not disappear because repository metadata says CC BY; human resolves conflict.',response_binding('PGC_ADHD_README')+' | '+response_binding('PGC_SCZ_README'))
fact('CRC_ACADEMIC','Colorectal GCST90255675','https://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90255001-GCST90256000/GCST90255675/README.txt','LIVE_HTTP200_README_AND_YAML','Exact README/YAML specifies European subset and academic license; data cannot be used by for-profit entities.','Modified CC BY-NC4.0 stated; short README refers to full academic-license details that are not supplied here.','Fernandez-Rozadilla2023 plus source QC references as appropriate.','Human supplies/reconciles complete modified academic-license terms and proposed use/release; generic Catalog CC0 does not apply.',response_binding('colorectal_README')+' | '+response_binding('colorectal_metadata_yaml'))
fact('EDINBURGH_MDD','Edinburgh Howard2019','https://datashare.ed.ac.uk/items/e8734c04-98d0-4a4d-87b7-058aedfdf822','LIVE_HTTP200_ITEM_JSON_AND_LICENSE','Exact DOI-resolved item metadata and linked end-user license identify CC BY4.0; public genome-wide file excludes23andMe.','Explicit item CC BY4.0; full23andMe statistics remain separate restricted-access material.','Cite dataset DOI10.7488/ds/2458 and Howard2019.','Human checks attribution/owner authority and keeps the frozen no23andMe scope; no restricted-data request.',response_binding('edinburgh_mdd_item_metadata')+' | '+response_binding('edinburgh_mdd_enduser_license'))
fact('NEALE_R2','Neale round2','https://www.nealelab.is/uk-biobank/faq','LIVE_OFFICIAL_WEB_TEXT','FAQ permits free download/use without restriction, including commercial use.','No explicit named redistribution license found in inspected FAQ; do not substitute Pan-UKB license for distinct2018 source.','Round2 cite dated Neale UK Biobank page.','Human records applicable reuse/UKB conditions for exact46_irnt object before raw hosting.')
fact('OPENGWAS_SBP','OpenGWAS ieu-b-38','https://opengwas.io/about','LIVE_OFFICIAL_WEB_TEXT_AND_DATASET_HTML','Public GWAS-VCF downloads documented; original data citation required; exact dataset HTML has dynamic placeholder fields.','No exact dataset-level redistribution license established by inspected page.','Cite Evangelou2018 and OpenGWAS/API/VCF references actually used.','Human checks original source-owner conditions and exact dataset license; open-source-files wording is not an inferred CC0 grant.',response_binding('opengwas_ieu_b_38'))
fact('BCAC','BCAC breast2020','https://www.ccge.medschl.cam.ac.uk/breast-cancer-association-consortium-bcac/data-data-access/summary-results/gwas-summary-associations','ACCESS_FAILURE_WITH_OFFICIAL_INDEXED_AVAILABILITY','Official indexed Data Access page says GWAS summary results publicly available; direct page web access failed and shell DNS failed.','No exact redistribution license established from available evidence.','Zhang2020 and BCAC source page in frozen registry.','Human provides applicable exact download-page/license record; access success/hash does not confer permission.',response_binding('bcac_breast'))
fact('LDSC_GPL','LDSC code','https://github.com/bulik/ldsc/blob/master/LICENSE','LIVE_MASTER_LICENSE_AND_LOCAL_PINNED_BLOB','Current official license is GPLv3; local pinned6c673952 LICENSE blob733c072369ca77331f392c40da7404c85c36542c matches official master bytes.','GPL code terms apply to code; they do not license GWAS/reference data. Remote pinned URL404 retained separately.','Cite LDSC implementation/method; preserve license/notices if redistributed.','Human decides code-distribution compliance; no vendoring/relicensing in this pass.',response_binding('ldsc_master_license')+' | pinned_LICENSE_SHA256=d62f065830aa3739cc031156b9690805c7b2e811b4a178c8b4acd8725d561c94')
fact('UCSC_CHAIN','UCSC liftOver chain','https://genome.ucsc.edu/license/','LIVE_OFFICIAL_WEB_TEXT','UCSC says chain files can be linked/downloaded/used/redistributed only noncommercially; general data and tool licenses have exceptions.','Chain exception is source-specific; website availability does not erase it.','Cite UCSC and exact chain source/version.','Human confirms exact chain applicability/noncommercial scope and upstream genome/track restrictions; do not assign code GPL to chain.')
fact('IGSR_REFERENCE','1000G/HapMap3/LD references','https://www.internationalgenome.org/IGSR_disclaimer/','LIVE_OFFICIAL_WEB_TEXT','1000G data no longer under embargo; IGSR owners/restrictions vary and accompanying reuse statements must be checked.','No blanket license for separately derived LDSC LD scores/HapMap3 maps established by general IGSR statement.','Cite1000G/IGSR and exact reference generator/resource.','Human verifies exact derived reference-package/map reuse conditions; no reference bodies inspected.')
fact('PROJECT_OWNER','Project artifacts','LOCAL_ROOT_LICENSE_INVENTORY','LOCAL_METADATA_ONLY','No root LICENSE exists at review time; ownership/author authority not inferred.','No general open-source grant established by repository access.','Preserve upstream citations; project-author attribution determined by humans.','Human owners choose any license/archive/DOI and confirm authority for project-generated code/tables/figures.')
fact('OUP_CACHE','Publisher/literature caches','https://academic.oup.com/pages/purchasing/rights-and-permissions','LIVE_OFFICIAL_WEB_TEXT','OUP directs journal-content reuse through item permissions/RightsLink; copyright holders and exceptions vary.','Public availability is not a blanket fulltext/figure/workbook redistribution permission.','Cite original article and identify item-specific license/credit lines.','Keep raw review caches outside public artifact release; humans approve any specific republication after exact terms.')
fact('STROBE_CACHE','STROBE checklist cache','https://www.strobe-statement.org/','LIVE_OFFICIAL_INDEXED_TEXT_DIRECT_TIMEOUT','Official page allows download, says original authors hold copyright and asks contact for republication/extension/translation.','Do not infer blanket republication entitlement from open-access download.','Cite STROBE authors/official checklist source.','Existing factual crosswalk stays compact; human checks permission if republishing actual checklist text; no contact made.')
fact('STREGA_CACHE','STREGA PLOS2009','https://journals.plos.org/plosmedicine/article?id=10.1371/journal.pmed.1000022','LIVE_OFFICIAL_WEB_TEXT','Exact PLOS article declares Creative Commons Public Domain terms.','Item-specific declaration does not extend to other articles/checklists/GWAS files.','Cite Little et al2009 DOI10.1371/journal.pmed.1000022.','Preserve exact-item attribution/provenance; this review releases no cached fulltext.')
# Facts are paraphrases; hashes below bind the compact fact records, not unavailable web HTML bodies.
for f in POLICIES:f['compact_fact_sha256']=hashlib.sha256(json.dumps(f,sort_keys=True).encode()).hexdigest()
table(S/'source_policy_public_facts_v4_1.tsv',POLICIES)
rows=[];pgc_ids={'trubetskoy_2022_scz_eur':'figshare_scz_v7','mullins_2021_bipolar_eur':'figshare_bipolar_v2','demontis_2023_adhd_eur':'figshare_adhd_v1'}
def add(collection,index,trait,source,page,url,size,body_sha,body_md5,manifest,policy,license_text,exactproof='',accession=''):
 rows.append(dict(collection=collection,index=index,trait_id=trait,source_id=source,accession=accession,source_page_url=page,frozen_source_url=url,frozen_size_bytes=size,historical_or_registry_body_sha256=body_sha,historical_or_metadata_body_md5=body_md5,membership_manifest=str(manifest),membership_manifest_sha256=sha(manifest),policy_ids=policy,observed_license_mark=license_text,policy_record_evidence=exactproof,public_observation_utc=NOW,project_raw_body_publication_status='PROHIBITED_UNTIL_SOURCE_RIGHTS_AND_HUMAN_RELEASE_AUTHORITY_CLEARED',body_hash_not_a_rights_grant=True))
for i,r in enumerate(core['rows'],1):
 q=reg[r['source_id']];source=r['source_id'];page=q['source_page_url'];a=re.search(r'GCST\d+',page);proof='';mark='';policy=''
 if a:
  id=a.group();receipt=responses[id];assert receipt['http_code']=='200' and receipt['returncode']==0
  meta=json.loads(Path(receipt['path']).read_text());assert meta['accession_id']==id
  mark=meta['terms_of_license'];proof=response_binding(id);policy='CATALOG_DEFAULT;EBI_OWNER_TERMS'
  if id=='GCST90255675':policy+=';CRC_ACADEMIC'
 elif source.startswith('finngen_'):policy='FINNGEN_R9;FINNGEN_FORM';mark='NO_EXPLICIT_REDISTRIBUTION_GRANT_OBSERVED'
 elif source in pgc_ids:
  id=pgc_ids[source];j=json.loads(Path(responses[id]['path']).read_text());fid=int(q['download_url'].rsplit('/',1)[-1]);f=next(f for f in j['files'] if f['id']==fid)
  assert f['size']==int(q['archive_bytes']);proof=response_binding(id)+' | exact_file_id='+str(fid);mark=j['license']['name'];policy='PGC_TERMS;PGC_FIGSHARE'+('' if source=='mullins_2021_bipolar_eur' else ';PGC_READMES')
 elif source=='howard_2019_mdd_no23andme':policy='EDINBURGH_MDD';mark='CC BY4.0_EXACT_ITEM';proof=response_binding('edinburgh_mdd_item_metadata')
 elif source=='jansen_2019_insomnia_ukb':policy='CNCR_JANSEN';mark='CC BY-NC-SA4.0_PLUS_PAGE_CONDITIONS'
 elif source=='neale_2018_left_grip_strength':policy='NEALE_R2';mark='UNRESTRICTED_USE_STATEMENT_NO_NAMED_DATASET_LICENSE'
 elif source=='evangelou_2018_sbp_opengwas':policy='OPENGWAS_SBP';mark='EXACT_DATASET_LICENSE_NOT_ESTABLISHED'
 elif source=='bcac_2020_overall_breast_cancer':policy='BCAC';mark='EXACT_SOURCE_LICENSE_ACCESS_FAILED'
 else:assert q['source_page_url']=='https://www.kp4cd.org/node/235';policy='SDKP';mark='PORTAL_ANALYTIC_USE_ONLY_UNDERLYING_REDISTRIBUTION_UNRESOLVED'
 add('core45',i,r['trait_id'],source,page,q['download_url'],q['archive_bytes'],q['archive_sha256'],'',core_path,policy,mark,proof,a.group() if a else '')
for m in ext['members']:
 assert m['extension_trait_id'].startswith('panukbb_') and 'pan-ukb-us-east-1.s3.amazonaws.com' in m['url']
 add('extension100',m['index'],m['extension_trait_id'],m['extension_trait_id'],'https://pan.ukbb.broadinstitute.org/downloads/index.html',m['url'],m['expected_bytes'],m['expected_sha256'],m['expected_md5'],ext_path,'PAN_UKB','CC BY4.0_SOURCE_GWAS_RESULTS')
for m in val['members']:
 h=m['historical_source_body'];source=m['source_id'];a=re.search(r'GCST\d+',source)
 if a:
  id=a.group();x=json.loads(Path(responses[id]['path']).read_text());assert x['accession_id']==id
  page='https://www.ebi.ac.uk/gwas/studies/'+id;policy='CATALOG_DEFAULT;EBI_OWNER_TERMS';mark=x['terms_of_license'];proof=response_binding(id)
 else:page='https://finngen.gitbook.io/documentation/data-download';policy='FINNGEN_R13;FINNGEN_FORM';mark='NO_EXPLICIT_REDISTRIBUTION_GRANT_OBSERVED';proof=''
 add('validation13',m['index'],m.get('source_label',source),source,page,h['source'],h['observed_size_bytes'],h['observed_sha256'],h['observed_md5'],val_path,policy,mark,proof,a.group() if a else '')
headers=dict(re.findall(r'^([^:\n]+):\s*([^\n]+)$',sleep['response_headers'],re.M));generation=headers['x-goog-generation'].strip();size=headers['content-length'].strip();md5=headers['etag'].strip().strip('"')
add('new_Finn_R13_insomnia',1,'insomnia','FinnGen_R13_F5_INSOMNIA','https://finngen.gitbook.io/documentation/data-download',sleep['url']+'?generation='+generation,size,fg_plan['source_identity']['sha256'],md5,fg_plan_path,'FINNGEN_R13;FINNGEN_FORM','NO_EXPLICIT_REDISTRIBUTION_GRANT_OBSERVED','Source SHA from existing preprocessing-plan metadata only; HEAD receipt SHA256='+sha(sleep_path))
assert len(rows)==159 and len({(r['collection'],r['index']) for r in rows})==159
table(S/'source_policy_exact_source_ledger_v4_1.tsv',rows)
# Auxiliary previously reviewed clinical insomnia source is kept separate from exact159 membership; no scientific admission.
a=responses['GCST90475826'];j=json.loads(Path(a['path']).read_text());save(S/'source_policy_auxiliary_MVP_insomnia_metadata_v4_1.json',{'schema':'auxiliary_previously_reviewed_MVP_rights_metadata_v4_1','not_member_of_exact159_current_source_rows':True,'accession':'GCST90475826','terms_of_license':j['terms_of_license'],'policy_ids':['CATALOG_DEFAULT','EBI_OWNER_TERMS'],'exact_evidence':a,'scientific_source_substitution_or_admission':False})
gaps=[
 ('H01','All source and project groups','Human release owner records institutional authority and intended public artifact inventory; raw-body hosting remains out of scope until cleared.','Project publication authority; not inferred from download/hash.'),
 ('H02','EBI-term core accessions and both MVP validation accessions; auxiliary clinical MVP','Reconcile original-owner and adjacent README conditions for exact records before raw redistribution; preserve accession exceptions.','No blanket CC0 or new sublicense.'),
 ('H03','PGC scz,bipolar,adhd','Resolve CC BY Figshare/item fields versus official PGC/release conditions; ADHD README explicitly forbids public reposting.','Do not choose permissive interpretation; no contacting in this pass.'),
 ('H04','GCST90255675 colorectal','Provide complete modified academic-license details; observed short README bans for-profit entities and references fuller terms.','Source-specific academic/noncommercial constraint.'),
 ('H05','FinnGen six core R9, eleven validation R13 and new R13 insomnia','Record applicable registration/agreement and institutional compliance; clarify redistribution/derivative scope if raw release proposed.','Public access route is verified; registration status is not invented.'),
 ('H06','Jansen2019 CNCR UKB-only insomnia','Confirm exact-file license applicability and noncommercial/nonstigmatizing/attribution/share-alike compliance for proposed reuse.','No23andMe source switch or commercial permission inferred.'),
 ('H07','Five original Sleep Portal source files','Verify underlying file-owner redistribution terms; retain portal and study citation.','Portal grants analytic use; no blanket raw data license.'),
 ('H08','BCAC2020 breast','Supply exact official license/download conditions: live direct page failed; indexed public availability is not a license.','Access failure remains explicit, no generic license substitution.'),
 ('H09','OpenGWAS ieu-b-38 and Neale round2 grip','Confirm exact object/source-owner redistribution conditions; Neale use statement is permissive but no named dataset license was observed.','Do not borrow Pan-UKB/EBI licenses across sources.'),
 ('H10','LDSC, LD/HapMap3/maps and UCSC chain dependencies','Preserve GPL code notices; separately verify exact derived-reference rights and noncommercial chain scope.','Code license does not relicense input data.'),
 ('H11','Project-authored code/tables/figures','Human owners establish authorship/ownership, any broad license and archive/DOI authority; root LICENSE absent.','No open-source grant invented.'),
 ('H12','Articles/supplements and journal/checklist caches','Check exact item licenses/permissions before republishing text/figures/workbooks/checklists; retain raw caches outside public release.','PLOS STREGA declaration is item-specific; STROBE requests contact for republication, no contact undertaken.')]
table(S/'source_policy_human_gaps_v4_1.tsv',[dict(gap_id=id,source_scope=scope,human_evidence_needed=need,reason=why,status='HUMAN_DECISION_OR_SOURCE_SPECIFIC_RECORD_REQUIRED') for id,scope,need,why in gaps])
oldgroups=list(csv.DictReader((S/'source_rights_evidence_gaps_v4.tsv').open(),delimiter='\t'))
cross=[('PAN_UKB','LIVE_SPECIFIC_LICENSE_AND_CITATION_VERIFIED'),('FINNGEN_R9;FINNGEN_R13;FINNGEN_FORM','LIVE_ACCESS_CITATION_FORM_VERIFIED_REDISTRIBUTION_UNRESOLVED'),('CATALOG_DEFAULT;EBI_OWNER_TERMS','EXACT_MVP_EXCEPTION_VERIFIED_NOT_CC0'),('SDKP;CNCR_JANSEN','LIVE_PORTAL_ANALYTIC_USE_AND_CNCR_RESTRICTED_LICENSE_VERIFIED'),('LDSC_GPL;UCSC_CHAIN;IGSR_REFERENCE','CODE_LICENSE_VERIFIED_REFERENCE_SOURCE_GAPS_REMAIN'),('PROJECT_OWNER','ROOT_LICENSE_ABSENT_HUMAN_AUTHORITY_REQUIRED'),('OUP_CACHE','ITEM_SPECIFIC_RIGHTS_REQUIRED_CACHE_EXCLUDED'),('OUP_CACHE;STROBE_CACHE;STREGA_CACHE','CURRENT_ITEM_POLICY_FACTS_VERIFIED_CACHE_EXCLUDED')]
table(S/'source_policy_original8group_crosswalk_v4_1.tsv',[dict(original_group=o['source_group'],original_status=o['current_audit_status'],current_policy_ids=c[0],current_status=c[1],original_ledger_sha256=sha(S/'source_rights_evidence_gaps_v4.tsv'),original_ledger_preserved=True) for o,c in zip(oldgroups,cross)])
failures=[{k:r[k] for k in ['id','url','retrieved_utc','returncode','http_code','stderr','bytes','sha256']} for r in responses.values() if r['returncode'] or r['http_code']!='200']
web_failures=[dict(url=u,observed_utc=NOW,mode=m,status=s) for u,m,s in [
 ('https://www.ebi.ac.uk/gwas/rest/api/v2/studies/GCST90479148','WEB_OPEN','UNAVAILABLE_VIA_WEB_TOOL_RESOLVED_BY_BOUNDED_HTTP200_JSON'),
 ('https://www.ebi.ac.uk/gwas/rest/api/v2/studies/GCST90479330','WEB_OPEN','UNAVAILABLE_VIA_WEB_TOOL_RESOLVED_BY_BOUNDED_HTTP200_JSON'),
 ('https://www.ebi.ac.uk/gwas/studies/GCST90479148','WEB_RENDERED_TEMPLATE','EMPTY_DYNAMIC_TERMS_NOT_LICENSE_EVIDENCE'),
 ('https://www.ccge.medschl.cam.ac.uk/breast-cancer-association-consortium-bcac/data-data-access','WEB_OPEN','HTTP403_ACCESS_FAILURE'),
 ('https://www.strobe-statement.org/','WEB_OPEN','TIMEOUT_INDEXED_OFFICIAL_TEXT_AVAILABLE'),
 ('https://www.internationalgenome.org/data-portal/data-use-policy','WEB_OPEN','UNAVAILABLE_RESOLVED_BY_OFFICIAL_DISCLAIMER_PAGE'),
 ('https://hgdownload.soe.ucsc.edu/goldenPath/hg38/liftOver/README.txt','WEB_OPEN','UNAVAILABLE_OFFICIAL_LICENSING_PAGE_AVAILABLE'),
 ('https://opengwas.io/terms','WEB_OPEN','UNAVAILABLE_ABOUT_AND_EXACT_DATASET_HTML_AVAILABLE')]]
core_catalog=[r for r in rows if r['collection']=='core45' and r['accession']];marks={r['accession']:r['observed_license_mark'] for r in core_catalog}
counts={'core_rows':45,'core_unique_source_ids':43,'extension_rows':100,'validation_rows':13,'new_Finn_R13_insomnia_rows':1,'exact_membership_rows':159,'distinct_core_catalog_accessions':len(marks),'core_catalog_CC0':sum('zero/1.0' in x for x in marks.values()),'core_catalog_EBI_terms':sum(x==EBI for x in marks.values()),'core_catalog_README_exception':sum(x=='Please Refer to ReadMe File' for x in marks.values()),'policy_facts':len(POLICIES),'human_gaps':len(gaps),'metadata_requests':len(responses),'metadata_retained_response_bytes':sum(r['bytes'] for r in responses.values()),'metadata_failed_requests':len(failures)}
assert counts['core_catalog_CC0']==6 and counts['core_catalog_EBI_terms']==17 and counts['core_catalog_README_exception']==1
save(S/'source_policy_review_evidence_receipt_v4_1.json',{'schema':'versioned_public_source_policy_evidence_receipt_v4_1','recorded_utc':NOW,'local_review_date':'2026-10-09','timezone':'America/Chicago','counts':counts,'input_metadata_sha256_before':before,'input_metadata_sha256_after':{str(p):sha(p) for p in inputs},'all_input_metadata_unchanged':all(sha(p)==before[str(p)] for p in inputs),'response_identity_sha256':{r['path']:r['sha256'] for r in responses.values()},'shell_access_failures':failures,'web_access_failures':web_failures,'web_policy_proof_note':'URL, date, mode and hashed compact factual paraphrases; web HTML body digests are unavailable and are not invented. Cached exact JSON/README responses have separate actual body SHA256.','GWAS_or_reference_body_reads_or_downloads':0,'native_or_raw_acquisition_audits_repeated':False,'investigators_contacted_or_forms_submitted':False,'protected_inputs_or_policies_changed':False,'root_LICENSE_exists':(ROOT/'LICENSE').exists(),'raw_cache_release':'SSD review caches excluded; compact facts/receipts only eligible technical deliverables; project raw-body publication prohibited until rights cleared.'})
print(json.dumps(counts,indent=2))
