#!/usr/bin/env python3
"""Reproducible access accounting and phenotype-specific feasibility matrix."""
import csv,hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[4];AREA=ROOT/'brain6/translational_psychiatry_research_v1/research_v1';RAW=ROOT/'work/tp-literature-20261007'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def tsv(p,rows,fields=None):
 if fields is None:fields=list(rows[0])
 with p.open('w',newline='') as f:
  w=csv.DictWriter(f,fields,delimiter='\t',extrasaction='ignore');w.writeheader();w.writerows(rows)
def main():
 receipts=[]
 for kind in ['search','extras']:
  for r in json.loads((AREA/f'novelty/{kind}_acquisition_receipts.json').read_text()):
   receipts.append(dict(object_id=r['id'],source_url=r['url'],access=r['access'],retrieved_utc=r['retrieved_utc'],status=r['status'],http_status=r.get('http_status'),max_bytes=r['max_bytes'],actual_bytes=r.get('bytes'),sha256=r.get('sha256'),path=r['planned_path'],active_blocker=r['status']=='UNAVAILABLE' and r['id'] not in ['schipper_v2'],note='Schipper full HTML 403 resolved through official API-advertised JATS plus public supplements' if r['id']=='schipper_v2' else 'Object accessibility does not attest complete source cohort independence'))
 for r in json.loads((AREA/'sources/fixed_variant_acquisition_receipts.json').read_text()):
  receipts.append(dict(object_id=r['rsid']+'_FinnGen_R13_fixed',source_url=r['url'],access='ORDINARY_ADVERTISED_PUBLIC_BROWSER_API',retrieved_utc=r['retrieved_utc'],status=r['status'],http_status=r.get('http_status'),max_bytes=r['max_bytes'],actual_bytes=r['bytes'],sha256=r.get('sha256'),path=r['raw_path'],active_blocker=r['status']!='RETRIEVED',note='PheWAS matrix filtered; exact planned phenotype null fields remain missing'))
 tsv(AREA/'sources/PUBLIC_ACQUISITION_LEDGER.tsv',receipts)
 # Explicit distinction: display API metadata count is not per-variant observed N.
 native={p['phenocode']:p for p in json.loads((RAW/'finngen_r13_phenotypes.json').read_text())};feasible=[]
 trait_defs={
 'F5_INSOMNIA':('insomnia','ICD10 F51.0/G47.0; primary outpatient/hospital/death registries; controls exclude F5_SLEEP','risteys_r13_f5_insomnia.html'),
 'F5_ADHD':('adhd','ICD10 F90.0; hospital/death, ICD9 3140; controls exclude F5_BEHEMOCHILD','risteys_r13_adhd.html'),
 'F5_DEPRESSIO':('mdd','ICD10 F32/F33; hospital/death; controls exclude F5_MOOD; includes psychotic depression','risteys_r13_f5_depressio.html'),
 }
 for code,(trait,definition,source) in trait_defs.items():
  p=native[code];nc=p['num_cases'];nn=p['num_controls']
  feasible.append(dict(source_id='FinnGen_R13_'+code,trait=trait,release='R13; public 2026-06-02',source_accession=code,doi='10.1038/s41586-022-05473-8',phenotype_definition=definition,cases=nc,controls=nn,n_total=nc+nn,neff_count_formula=4*nc*nn/(nc+nn),n_semantics='Endpoint case/control metadata, not variant-level observed N',cohorts='Finnish biobanks; endpoint-specific subset after QC; complete overlap matrix with discovery not established',ancestry='Finnish population; source-defined PCs and relatedness; no equivalence assumed to generic 1000G EUR',age='Endpoint age distribution publicly described in R13 Risteys; GWAS row-specific distribution not returned',sex='Overall R13 281909 females/218277 males; endpoint-specific GWAS sex counts not returned',build='GRCh38',effect_allele='ALT',effect_metric='Additive log OR; official R13 REGENIE v3.3',native_fields='beta,sebeta,pval,maf(ALT AF),maf_case,maf_control,n_case,n_control,n_sample',variant_n='Not verified as per-variant observed N; do not substitute annotation NS',coverage='3 exact fixed variants acquired; public matrix filtered; dense region coverage unknown',source_url='https://r13.finngen.fi/api/phenos',phenotype_url='https://r13.risteys.finngen.fi/endpoints/'+code,terms_url='https://www.finngen.fi/en/access_results',terms='Ordinary public browser use; cite FinnGen/Kurki2023 and acknowledge participants/investigators. Bulk summary access requires form; not used.',source_sha256=sha(RAW/'finngen_r13_phenotypes.json'),phenotype_sha256=sha(RAW/source),classification='PHENOTYPE_SENSITIVITY',independence='UNVERIFIED_WITH_DISCOVERY',eligibility='POINT_SENSITIVITY_ELIGIBLE_WHEN_NATIVE_FIELDS_PRESENT; DENSE_COLLOCATION_INELIGIBLE'))
 for source,doi,trait,pheno,note,file in [
 ('Partners_Biobank_2020','10.1038/s41598-020-63792-0','insomnia','EHR ICD-defined insomnia, mixed sleep codes','Exact selected loci not published as a complete native summary source; summary statistics on corresponding-author request; IRB-protected underlying data','partners_insomnia.html'),
 ('STARRS_2018','10.1038/s41380-018-0033-5','insomnia','Survey-defined lifetime insomnia; US Army NSS1/NSS2/PPDS; EUR/AFR/LAT','3237 cases/14414 controls across ancestry/study meta-analysis; EUR-specific counts/source full summary access and overlap must be established before analysis','starrs_insomnia.html'),
 ('HUNT_only_candidate','','insomnia','Exact source release/clinical definition unverified','No complete authorized compatible source object identified; do not substitute HUNT+UKB mixed cohort summaries as independent',''),
 ('PGC_MDD_2025_noUKB','10.1016/j.cell.2024.12.002','mdd','Clinical/broad depressive phenotype mix; noUKB release','Prior cohort audit finds nine PGC cohort names reused from Howard2019; not independent two-trait replication; original sleep reuse also disqualifies that label',''),
 ]:
  feasible.append(dict(source_id=source,trait=trait,release='Source-specific; see exact study',source_accession='UNRESOLVED',doi=doi,phenotype_definition=pheno,cases='UNVERIFIED_STRATUM',controls='UNVERIFIED_STRATUM',n_total='UNVERIFIED_STRATUM',neff_count_formula='',n_semantics='Must establish source stratum and variant-level N',cohorts='UNVERIFIED_WITH_DISCOVERY',ancestry='Study-specific; not inferred solely from label',age='UNVERIFIED',sex='UNVERIFIED',build='UNVERIFIED',effect_allele='UNVERIFIED',effect_metric='UNVERIFIED',native_fields='NO_COMPLETE_ELIGIBLE_OBJECT_ACQUIRED',variant_n='UNVERIFIED',coverage='No eligible dense paired source acquired',source_url='https://doi.org/'+doi if doi else '',phenotype_url='',terms_url='Study data-availability statement',terms=note,source_sha256=sha(RAW/file) if file else '',phenotype_sha256='',classification='PARTIAL_COHORT_OVERLAP' if source.startswith('PGC') else 'UNVERIFIED',independence='UNVERIFIED_WITH_DISCOVERY',eligibility='BLOCKED_ACCESS_OR_SOURCE_ELIGIBILITY'))
 for row in feasible:
  if row['source_id']=='Partners_Biobank_2020':
   row.update(cases=3135,controls=14920,n_total=18055,neff_count_formula=4*3135*14920/18055,n_semantics='Published European patient-cohort total; per-variant observed N not acquired',cohorts='Partners Biobank patient cohort; control patients lack recorded insomnia or other sleep disorder symptoms',ancestry='European ancestry per primary article; HRC imputation',coverage='5508534 autosomal biallelic SNPs after MAF>=.01/INFO>.8/callrate>.98 QC; no complete authorized summary object acquired')
  elif row['source_id']=='STARRS_2018':
   row.update(cases='3237_ALL_ANCESTRY;EUR_EXACT_UNRESOLVED',controls='14414_ALL_ANCESTRY;EUR_EXACT_UNRESOLVED',n_total='17651_ALL_ANCESTRY;EUR11473_TABLE1',n_semantics='Main abstract all-ancestry cases/controls; Table1 EUR cohort totals4756/1817/4900; do not derive integer cases from rounded prevalence',cohorts='NSS1/NSS2/PPDS, US Army soldiers; phenotype lifetime DSM5-approximate Brief Insomnia Questionnaire',ancestry='EUR/AFR/LAT analyzed separately then meta-analyzed; EUR native GWAS source not acquired',age='All-ancestry cohort mean21.0/20.3/26.0 years, not stratum-specific',sex='All-ancestry cohort male81.4%/77.8%/92.8%, not stratum-specific',build='GRCh37/hg19 explicitly reported in primary Table2')
 tsv(AREA/'sources/SOURCE_FEASIBILITY.tsv',feasible)
 r=list(csv.DictReader((AREA/'sources/fixed_variant_results_corrected.tsv').open(),delimiter='\t'));rep=[]
 for x in r:
  rep.append(dict(option_id=x['slot_id'],sleep_source='FinnGen_R13_F5_INSOMNIA',outcome_source='FinnGen_R13_'+x['outcome_code'],classification='PHENOTYPE_SENSITIVITY',participant_independence='UNVERIFIED',sleep_reused_from_discovery=False,phenotype_match='Clinical registry phenotypes differ from discovery',eligible_data='Exact frozen point only; source P fields required',planned_family_size=4,decision=x['decision'],p_conjunction=x['conjunction_p'],p_bonferroni=x['bonferroni_p'],source_manifest='sources/FIXED_VARIANT_FINGEN_MANIFEST.json',next_action='Parent independently validate calculations; no shared-causal/independent replication claim'))
 for sid,psy in [('Partners_Biobank_2020','FinnGen_R13_F5_ADHD'),('Partners_Biobank_2020','FinnGen_R13_F5_DEPRESSIO'),('STARRS_2018','FinnGen_R13_F5_ADHD'),('STARRS_2018','FinnGen_R13_F5_DEPRESSIO'),('HUNT_only_candidate','PGC_MDD_2025_noUKB')]:
  rep.append(dict(option_id=sid+'__'+psy,sleep_source=sid,outcome_source=psy,classification='UNVERIFIED',participant_independence='UNVERIFIED; must audit every discovery/replication component and paired overlap',sleep_reused_from_discovery=False,phenotype_match='Study definitions differ; harmonization and phenotype-specific interpretation required',eligible_data='No fully eligible two-trait dense pair acquired',planned_family_size='NOT_FROZEN_NOT_RUN',decision='BLOCKED_ACCESS_OR_ELIGIBILITY',p_conjunction='',p_bonferroni='',source_manifest='sources/SOURCE_FEASIBILITY.tsv',next_action='Exact investigator request draft; acquire only after access authorization and bounded manifest'))
 rep.append(dict(option_id='Original_UKB_INS__FinnGen_Psych',sleep_source='Original Brain6 UKB insomnia',outcome_source='FinnGen R13 ADHD/MDD',classification='UNVERIFIED',participant_independence='Outcome independence UNVERIFIED; original sleep reused',sleep_reused_from_discovery=True,phenotype_match='Only outcome changed; at most INDEPENDENT_ONE_TRAIT_ONLY if outcome independence later verified',eligible_data='No regional experiment run',planned_family_size='NOT_FROZEN_NOT_RUN',decision='NOT_RUN',p_conjunction='',p_bonferroni='',source_manifest='sources/SOURCE_FEASIBILITY.tsv',next_action='No two-trait independence wording even if outcome cohort proven distinct'))
 tsv(AREA/'REPLICATION_MASTER.tsv',rep)
 access=[
 dict(study='Xue_PMID41065713',doi='10.1093/sleep/zsaf317',required_object='Complete methods and exact SNP/locus supplement',source_url='https://academic.oup.com/sleep/article/49/1/zsaf317/8279895',attempt='Publisher public article-minimal preview retrieved; ordinary full article route unavailable, no supplement object link in preview',status='ACTIVE_UNRESOLVED',receipt='novelty/extras_acquisition_receipts.json: xue_publisher_public_minimal',source_sha256=sha(RAW/'xue_publisher_public_minimal.html'),impact='Cannot exclude Xue prior signal at any unreviewed locus; no novelty from absence',legitimate_next_action='Authorized institutional full-text access or investigator-provided supplement; no access bypass/contact sent'),
 dict(study='Lin_2026',doi='10.1007/s00335-026-10232-5',required_object='Subscription main text, detailed source cohort reconciliation',source_url='https://link.springer.com/article/10.1007/s00335-026-10232-5',attempt='Public publisher preview and two explicitly linked supplements retrieved successfully',status='MAIN_TEXT_UNRESOLVED_LOCUS_SUPPLEMENTS_RESOLVED',receipt='novelty/extras_acquisition_receipts.json: lin_article/lin_supp1/lin_supp2',source_sha256=sha(RAW/'lin_supp1.xlsx'),impact='Exact loci/build available; source ADHD PMID/N inconsistency remains; full main text not required to observe published locus recurrence',legitimate_next_action='Authorized full-text reading plus source reconciliation, no independent cohort claim inferred'),
 dict(study='Schipper_v2',doi='10.1101/2025.10.18.25338281',required_object='Current version main text and supplements',source_url='https://api.biorxiv.org/details/medrxiv/10.1101/2025.10.18.25338281/na/json',attempt='Ordinary v2 full HTML HTTP403; official API-advertised source XML and public XML-linked media success',status='RESOLVED_OFFICIAL_PUBLIC_SOURCE',receipt='novelty/extras_acquisition_receipts.json: schipper_v2_jats/schipper_v2_supp_tables/schipper_v2_supp_notes',source_sha256=sha(RAW/'schipper_v2_supp_tables.xlsx'),impact='Exact chr11 INS_DEP LAVA and low H4 now resolved; preprint status retained',legitimate_next_action='No further access action needed for extracted facts'),
 dict(study='Jia_2025',doi='10.1093/sleep/zsae209',required_object='Published main text and supplement',source_url='https://oup.silverchair-cdn.com/article-minimal/7750695',attempt='Publisher explicitly free main article and its linked supplement retrieved without authentication',status='RESOLVED_PUBLIC_PRIMARY_SOURCE',receipt='novelty/extras_acquisition_receipts.json: jia_publisher_public_minimal/jia_supp1',source_sha256=sha(RAW/'jia_supp1.docx'),impact='A/B prior INS_MDD and 10 protected long-sleep psychiatric regions resolved; alleles remain unreported in S3/S7',legitimate_next_action='No access bypass needed; biallelic identity still cannot be asserted solely from Jia rsID'),
 ]
 tsv(AREA/'UNRESOLVED_LITERATURE_ACCESS.tsv',access)
 # Automated triage is not full-text review. Preserve all priority papers not read.
 records=list(csv.DictReader((AREA/'novelty/search_records.tsv').open(),delimiter='\t'));reviewed={'10.1007/s00335-026-10232-5':'PUBLIC_PREVIEW_AND_COMPLETE_SUPPLEMENTS','10.1038/s41398-026-04166-4':'PUBLIC_MAIN_AND_SUPPLEMENTS_REUSED','10.1093/sleep/zsaf317':'PUBLIC_ABSTRACT_ONLY_ACCESS_BLOCKED','10.1101/2025.10.18.25338281':'OFFICIAL_VERSION_API_V2_JATS_AND_SUPPLEMENTS'}
 priority=[]
 for r in records:
  if r['screen']!='PRIORITIZE_FULLTEXT_COMPETITOR':continue
  priority.append(dict(doi=r['doi'],pmid=r['pmid'],title=r['title'],first_publication_date=r['first_publication_date'],review=reviewed.get(r['doi'],'TITLE_ABSTRACT_TRIAGE_ONLY_NOT_FULLTEXT_REVIEW'),novelty_implication='No novelty inferred from search omission or unread supplement',query_ids=r['query_ids']))
 tsv(AREA/'novelty/priority_screen_dispositions.tsv',priority)
 print('access objects',len(receipts),'source options',len(feasible),'replication options',len(rep),'priority dispositions',len(priority))
if __name__=='__main__':main()
