#!/usr/bin/env Rscript
# Outcome-blinded, MDD2025 trait-only LAVA pilot. Never writes to canonical v3.
suppressPackageStartupMessages(library(jsonlite)); suppressPackageStartupMessages(library(data.table)); suppressPackageStartupMessages(library(LAVA))
fail<-function(x)stop(x,call.=FALSE);need<-function(x,m)if(!isTRUE(x))fail(m);a<-commandArgs(trailingOnly=TRUE)
if(length(a)!=1L)fail('Usage: Rscript run_mdd2025_trait_pilot_v1.R CONFIG.json')
cfg<-fromJSON(a[[1]],simplifyVector=FALSE);need(as.character(packageVersion('LAVA'))=='0.1.5','LAVA version mismatch');need(cfg$analysis_id=='brain6_mdd2025_trait_only_pilot_v1','Unexpected analysis ID');need(!file.exists(cfg$output_tsv)&&!file.exists(cfg$summary_json),'Refusing to overwrite screen output');need(length(cfg$locus_ids)==as.integer(cfg$expected_loci)&&length(unique(unlist(cfg$locus_ids)))==as.integer(cfg$expected_loci),'Frozen locus batch mismatch')
# Exact roundoff-only patch used by canonical v3.
ns<-asNamespace('LAVA');original<-get('decompose.ld',envir=ns,inherits=FALSE);bl<-deparse(body(original),width.cutoff=500L);hit<-which(trimws(bl)=='M = t(R.base) %*% ld$ld %*% R.base');need(length(hit)==1L,'Pinned LAVA block decomposition source changed')
insert<-c('            asymmetry <- max(abs(M - t(M)))','            tolerance <- 100 * .Machine$double.eps * max(1, nrow(M)) * max(1, max(abs(M)))',"            if (!is.finite(asymmetry) || asymmetry > tolerance) stop('Material asymmetry in block-reduced LD matrix; refusing numerical symmetrization', call. = FALSE)",'            if (asymmetry > 0) M <- (M + t(M)) / 2');bl<-append(bl,insert,after=hit);patched<-original;body(patched)<-parse(text=paste(bl,collapse='\n'))[[1L]];environment(patched)<-ns;unlockBinding('decompose.ld',ns);assign('decompose.ld',patched,envir=ns);lockBinding('decompose.ld',ns)
set.seed(as.integer(cfg$random_seed));loci<-LAVA::read.loci(cfg$loci_file);policy<-cfg$execution_policy$locus_processing;up<-cfg$execution_policy$univariate
checkref<-get('check.reference',envir=ns,inherits=FALSE);loadref<-get('load.reference',envir=ns,inherits=FALSE);reference<-loadref(checkref(cfg$reference_prefix));readss<-get('read.sumstats.file',envir=ns,inherits=FALSE);harm<-get('harmonize.snps',envir=ns,inherits=FALSE);align<-get('align',envir=ns,inherits=FALSE)
trait<-cfg$trait_id;rows<-vector('list',length(cfg$locus_ids));threshold<-as.numeric(cfg$strict_gate_p)
for(i in seq_along(cfg$locus_ids)) {
 id<-as.character(cfg$locus_ids[[i]]);j<-match(id,as.character(loci$LOC));need(!is.na(j),'Locus missing');d<-file.path(cfg$input_root,paste0('locus_',id));info<-fread(file.path(d,'input_info.tsv'));need(nrow(info)==1L&&info$phenotype[[1]]==trait,'Input-info mismatch');info$filename<-file.path(d,info$filename);info$N<-info$cases+info$controls;info$prop_cases<-info$cases/info$N;info$binary<-!is.na(info$prop_cases)&info$prop_cases!=1
 res<-tryCatch({x<-new.env(parent=globalenv());x$info<-copy(info);x$P<-1L;x$reference<-reference;x$sample.overlap<-NULL;x$sum.stats<-setNames(list(readss(info$filename[[1]],trait)),trait);harm(x);align(x);msg<-capture.output(loc<-LAVA::process.locus(loci[j,,drop=FALSE],x,phenos=trait,min.K=as.integer(policy$min_K),prune.thresh=as.numeric(policy$prune_thresh),max.prop.K=as.numeric(policy$max_prop_K),drop.failed=isTRUE(policy$drop_failed),max.block.size=as.integer(policy$max_block_size),cap.estimates=isTRUE(policy$cap_estimates)))
  if(is.null(loc)){why<-if(any(grepl('Fewer than',msg,fixed=TRUE)))'FEWER_THAN_MIN_K_SHARED_REFERENCE_VARIANTS' else if(any(grepl('Negative variance estimate',msg,fixed=TRUE)))'LOW_LOCAL_H2_UNDERPOWERED' else 'LAVA_PROCESS_LOCUS_RETURNED_NULL';data.table(trait_id=trait,locus_id=id,status='NOT_RUN',n_snps=NA_integer_,n_components=NA_integer_,h2_obs=NA_real_,p=NA_real_,strict_gate_pass=FALSE,reason=why)} else {
  u<-as.data.table(LAVA::run.univ(loc,phenos=trait,cap.estimates=isTRUE(up$cap_estimates)));need(nrow(u)==1L&&is.finite(u$p[[1]])&&u$p[[1]]>=0&&u$p[[1]]<=1,'Invalid univariate result');data.table(trait_id=trait,locus_id=id,status='TESTED',n_snps=as.integer(loc$n.snps),n_components=as.integer(loc$K),h2_obs=as.numeric(u$h2.obs[[1]]),p=as.numeric(u$p[[1]]),strict_gate_pass=as.numeric(u$p[[1]])<threshold,reason='')}
 },error=function(e)data.table(trait_id=trait,locus_id=id,status='FAILED',n_snps=NA_integer_,n_components=NA_integer_,h2_obs=NA_real_,p=NA_real_,strict_gate_pass=FALSE,reason=substr(conditionMessage(e),1L,500L)))
 rows[[i]]<-res;if(i%%100L==0L)cat(sprintf('SCREEN_PROGRESS %d/%d\n',i,length(rows)))
}
out<-rbindlist(rows,use.names=TRUE);need(nrow(out)==as.integer(cfg$expected_loci)&&uniqueN(out$locus_id)==as.integer(cfg$expected_loci),'Incomplete output');need(!anyDuplicated(out$locus_id),'Duplicate loci');need(!any(out$status=='FAILED'),'Execution failure; do not promote');write.table(out,cfg$output_tsv,sep='\t',quote=FALSE,row.names=FALSE,na='NA');writeLines(toJSON(list(analysis_id=cfg$analysis_id,scope=cfg$scope,rows=nrow(out),tested=sum(out$status=='TESTED'),not_run=sum(out$status=='NOT_RUN'),failed=sum(out$status=='FAILED'),strict_gate_pass=sum(out$strict_gate_pass),threshold=threshold),auto_unbox=TRUE,pretty=TRUE),cfg$summary_json);cat(sprintf('SCREEN_COMPLETE tested=%d not_run=%d strict_gate_pass=%d\n',sum(out$status=='TESTED'),sum(out$status=='NOT_RUN'),sum(out$strict_gate_pass)))
