name: sleep-gwas-atlas-workflow
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - python=3.11.11
  - numpy=1.26.4
  - pandas=2.2.3
  - matplotlib=3.9.4
  - snakemake=8.30.0
  - plink=1.90b7.7
  - r-base=4.3.3
