#!/usr/bin/env python3
"""Generate fake GWAS sumstats — and fake LDSC logs — to smoke-test the
pipeline offline.

Sumstats mode is deliberately messy: mixed column names, OR instead of BETA,
indels, strand-ambiguous SNPs, MHC variants, duplicates, junk p-values. The
point is to prove 01_harmonize.py catches all of it.

    python3 make_test_data.py --out data/raw            # raw sumstats
    python3 make_test_data.py --logs                    # synthetic LDSC logs
    python3 make_test_data.py --logs --raw              # both

--logs writes into results/_smoketest/, NEVER results/logs/. That separation
is the whole point: synthetic output and real output must not be able to sit
in the same directory, because 05_collate.py globs a directory and does not
ask where the files came from.

The log values below are HARDCODED and deterministic. There is no RNG in this
path on purpose. Jittered fake numbers are what produced an orphan Figure 2
with invented rg values that looked entirely publishable; a rigid, obviously
artificial gradient cannot be mistaken for a result.
"""
import argparse
import os

import numpy as np
import pandas as pd

rng = np.random.default_rng(42)

SMOKE_BANNER = (
    "***********************************************************************\n"
    "*  SYNTHETIC SMOKE-TEST OUTPUT - NOT REAL LDSC RESULTS                *\n"
    "*  Generated by scripts/make_test_data.py --logs                      *\n"
    "*  Every number below is fabricated to exercise code paths. It is     *\n"
    "*  not an estimate of anything. Do not quote, plot, or present it.    *\n"
    "***********************************************************************\n"
)


def make(n=60000, style="beta"):
    chrom = rng.integers(1, 23, n).astype(str)
    bp = rng.integers(1, 250_000_000, n)
    a1 = rng.choice(list("ACGT"), n)
    a2 = np.array([rng.choice([x for x in "ACGT" if x != a]) for a in a1])
    frq = rng.uniform(0.005, 0.995, n)
    se = rng.uniform(0.01, 0.05, n)
    beta = rng.normal(0, 0.02, n)
    z = beta / se
    from scipy.stats import norm
    p = 2 * norm.sf(np.abs(z))

    df = pd.DataFrame({
        "SNP": [f"rs{i}" for i in range(n)],
        "CHR": chrom, "BP": bp, "A1": a1, "A2": a2,
        "FRQ": frq, "SE": se, "P": p,
        "INFO": rng.uniform(0.3, 1.0, n),
        "N": 400000,
    })
    if style == "or":
        df["OR"] = np.exp(beta)
        df = df.rename(columns={"SNP": "MarkerName", "A1": "Effect_allele",
                                "A2": "Other_allele", "FRQ": "EAF",
                                "SE": "StdErr", "P": "P-value"})
    else:
        df["BETA"] = beta

    # --- inject dirt ---------------------------------------------------------
    a1col = "Effect_allele" if "Effect_allele" in df else "A1"
    a2col = "Other_allele" if "Other_allele" in df else "A2"
    pcol = "P-value" if "P-value" in df else "P"

    df.loc[0:499, a1col] = "A"; df.loc[0:499, a2col] = "T"        # ambiguous
    df.loc[500:799, a1col] = "AT"                                  # indel
    df.loc[800:999, "CHR"] = "6"; df.loc[800:999, "BP"] = 28_000_000  # MHC
    df.loc[1000:1099, pcol] = np.nan                               # missing P
    df.loc[1100:1199, pcol] = 0.0                                  # invalid P
    df = pd.concat([df, df.iloc[2000:2300]], ignore_index=True)     # duplicates
    return df.sample(frac=1, random_state=1).reset_index(drop=True)


# --- synthetic LDSC logs ------------------------------------------------------

# Baseline h2 values for problem comparison and standard traits
PROBLEM_H2 = {
    "insomnia":          ("Liability", 0.0800, 0.0050, 1.0150, 0.0090, 1.0940, 1.1520, 0.0987),
    "insomnia_ukb":      ("Liability", 0.0800, 0.0050, 1.0150, 0.0090, 1.0940, 1.1520, 0.0987),
    "insomnia_full":     ("Liability", 0.0750, 0.0027, 1.0250, 0.0095, 1.1820, 1.3400, 0.0735),
    "sleepdur":          ("Observed",  0.0900, 0.0060, 1.0200, 0.0085, 1.1010, 1.1740, 0.1149),
    "shortsleep":        ("Liability", 0.0400, 0.0080, 1.3500, 0.0140, 1.4020, 1.4800, 0.7292),
    "shortsleep_dashti": ("Liability", 0.0400, 0.0080, 1.3500, 0.0140, 1.4020, 1.4800, 0.7292),
    "shortsleep_az":     ("Liability", 0.0250, 0.0060, 1.0500, 0.0110, 1.1200, 1.1900, 0.2500),
    "longsleep":         ("Liability", 0.0120, 0.0060, 1.0080, 0.0087, 1.0110, 1.0190, 0.4211),
    "longsleep_dashti":  ("Liability", 0.0120, 0.0060, 1.0080, 0.0087, 1.0110, 1.0190, 0.4211),
    "longsleep_az":      ("Liability", 0.0080, 0.0053, 1.0050, 0.0085, 1.0080, 1.0120, 0.4167),
}


def load_traits_config(config_path="config/traits.tsv"):
    if os.path.exists(config_path):
        return pd.read_csv(config_path, sep="\t")
    return None


def write_h2_logs(outdir, config_path="config/traits.tsv"):
    """One h2_<trait>.log per trait in config/traits.tsv."""
    df_config = load_traits_config(config_path)
    if df_config is not None:
        traits = df_config["trait_id"].tolist()
    else:
        traits = list(PROBLEM_H2.keys())

    written = []
    for idx, trait in enumerate(traits):
        if trait in PROBLEM_H2:
            scale, h2, se, icept, icept_se, lam, chi2, ratio = PROBLEM_H2[trait]
        else:
            scale = "Liability" if "continuous" not in str(df_config.loc[df_config["trait_id"]==trait, "type"].values[0]) else "Observed"
            # Deterministic, plausible synthetic values across 90 traits
            h2 = 0.05 + 0.001 * (idx % 25)
            se = 0.004 + 0.0001 * (idx % 10)
            icept = 1.01 + 0.002 * (idx % 15)
            icept_se = 0.008
            lam = 1.08 + 0.005 * (idx % 20)
            chi2 = 1.12 + 0.01 * (idx % 20)
            ratio = 0.10 + 0.01 * (idx % 15)

        body = (
            f"{SMOKE_BANNER}\n"
            f"Call: ldsc.py --h2 SYNTHETIC/{trait}.sumstats.gz\n\n"
            f"Total {scale} scale h2: {h2:.4f} ({se:.4f})\n"
            f"Lambda GC: {lam:.4f}\n"
            f"Mean Chi^2: {chi2:.4f}\n"
            f"Intercept: {icept:.4f} ({icept_se:.4f})\n"
            f"Ratio: {ratio:.4f} ({icept_se * 4:.4f})\n"
        )
        path = os.path.join(outdir, f"h2_{trait}.log")
        with open(path, "w") as fh:
            fh.write(body)
        written.append(path)
    return written


def write_rg_logs(outdir, config_path="config/traits.tsv"):
    """One rg_<sleeptrait>.log per sleep trait, running against all disease traits."""
    from scipy.stats import norm

    df_config = load_traits_config(config_path)
    if df_config is not None:
        sleep_traits = df_config[df_config["domain"] == "sleep"]["trait_id"].tolist()
        disease_traits = df_config[df_config["domain"] != "sleep"]["trait_id"].tolist()
    else:
        sleep_traits = ["insomnia", "sleepdur", "chronotype", "sleepiness"]
        disease_traits = ["mdd", "scz", "alz", "t2d", "bmi", "cad"]

    written = []
    rg_header = ("p1 p2 rg se z p h2_obs h2_obs_se h2_int h2_int_se "
                 "gcov_int gcov_int_se")

    for i, s in enumerate(sleep_traits):
        rows = []
        for j, d in enumerate(disease_traits):
            k = (i * len(disease_traits) + j)
            # Deterministic calculation spanning -0.45 to +0.45
            rg_val = -0.45 + (k % 40) * 0.023
            if rg_val > 0.45: rg_val = 0.45
            z_val = rg_val * 12.0
            if abs(z_val) < 0.1: z_val = 0.2
            se = abs(rg_val / z_val) if z_val != 0 else 0.05
            p = 2 * norm.sf(abs(z_val))
            rows.append(
                f"SYNTHETIC/{s}.sumstats.gz SYNTHETIC/{d}.sumstats.gz "
                f"{rg_val:.4f} {se:.4f} {z_val:.4f} {p:.4g} "
                f"0.0900 0.0055 1.0250 0.0095 0.0041 0.0060"
            )
        body = (
            f"{SMOKE_BANNER}\n"
            f"Call: ldsc.py --rg SYNTHETIC/{s}.sumstats.gz,...\n\n"
            "Summary of Genetic Correlation Results\n"
            f"{rg_header}\n" + "\n".join(rows) + "\n\n"
            "Analysis finished.\n"
        )
        path = os.path.join(outdir, f"rg_{s}.log")
        with open(path, "w") as fh:
            fh.write(body)
        written.append(path)
    return written


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="data/raw",
                    help="destination for raw sumstats")
    ap.add_argument("--config", default="config/traits.tsv",
                    help="path to traits.tsv configuration")
    ap.add_argument("--logs", action="store_true",
                    help="write synthetic LDSC h2/rg logs to --logdir")
    ap.add_argument("--logdir", default="results/_smoketest",
                    help="MUST stay separate from results/logs/")
    ap.add_argument("--raw", action="store_true",
                    help="write raw sumstats too when --logs is given")
    a = ap.parse_args()

    if os.path.normpath(a.logdir) == os.path.normpath("results/logs"):
        raise SystemExit(
            "ERROR: refusing to write synthetic logs into results/logs/.\n"
            "       Real and fake LDSC output must never share a directory —\n"
            "       05_collate.py globs the directory and cannot tell them apart."
        )

    if a.logs:
        os.makedirs(a.logdir, exist_ok=True)
        h2_written = write_h2_logs(a.logdir, a.config)
        rg_written = write_rg_logs(a.logdir, a.config)
        print(f"Wrote {len(h2_written)} h2 logs + {len(rg_written)} rg logs in {a.logdir}")
        print("Every value in them is fabricated to test the 90-trait pipeline.")

    if a.raw or not a.logs:
        os.makedirs(a.out, exist_ok=True)
        for trait, style, sepc in [("insomnia", "beta", "\t"), ("mdd", "or", " ")]:
            d = make(style=style)
            f = os.path.join(a.out, f"{trait}.txt.gz")
            d.to_csv(f, sep=sepc, index=False, compression="gzip")
            print(f"wrote {f}  ({len(d):,} rows, style={style})")
