#!/usr/bin/env python3
"""Generate fake GWAS sumstats — and fake LDSC logs — to smoke-test the
pipeline offline.

Sumstats mode is deliberately messy: mixed column names, OR instead of BETA,
indels, strand-ambiguous SNPs, MHC variants, duplicates, junk p-values. The
point is to prove 01_harmonize.py catches all of it.

    python3 make_test_data.py --out data/raw            # raw sumstats
    python3 make_test_data.py --logs                    # synthetic LDSC logs
    python3 make_test_data.py --logs --raw              # both

--logs writes into results/_smoketest/, NEVER results/logs/. That separation
is the whole point: synthetic output and real output must not be able to sit
in the same directory, because 05_collate.py globs a directory and does not
ask where the files came from.

The log values below are HARDCODED and deterministic. There is no RNG in this
path on purpose. Jittered fake numbers are what produced an orphan Figure 2
with invented rg values that looked entirely publishable; a rigid, obviously
artificial gradient cannot be mistaken for a result.
"""
import argparse
import os

import numpy as np
import pandas as pd

rng = np.random.default_rng(42)

SMOKE_BANNER = (
    "***********************************************************************\n"
    "*  SYNTHETIC SMOKE-TEST OUTPUT - NOT REAL LDSC RESULTS                *\n"
    "*  Generated by scripts/make_test_data.py --logs                      *\n"
    "*  Every number below is fabricated to exercise code paths. It is     *\n"
    "*  not an estimate of anything. Do not quote, plot, or present it.    *\n"
    "***********************************************************************\n"
)


def make(n=60000, style="beta"):
    chrom = rng.integers(1, 23, n).astype(str)
    bp = rng.integers(1, 250_000_000, n)
    a1 = rng.choice(list("ACGT"), n)
    a2 = np.array([rng.choice([x for x in "ACGT" if x != a]) for a in a1])
    frq = rng.uniform(0.005, 0.995, n)
    se = rng.uniform(0.01, 0.05, n)
    beta = rng.normal(0, 0.02, n)
    z = beta / se
    from scipy.stats import norm
    p = 2 * norm.sf(np.abs(z))

    df = pd.DataFrame({
        "SNP": [f"rs{i}" for i in range(n)],
        "CHR": chrom, "BP": bp, "A1": a1, "A2": a2,
        "FRQ": frq, "SE": se, "P": p,
        "INFO": rng.uniform(0.3, 1.0, n),
        "N": 400000,
    })
    if style == "or":
        df["OR"] = np.exp(beta)
        df = df.rename(columns={"SNP": "MarkerName", "A1": "Effect_allele",
                                "A2": "Other_allele", "FRQ": "EAF",
                                "SE": "StdErr", "P": "P-value"})
    else:
        df["BETA"] = beta

    # --- inject dirt ---------------------------------------------------------
    snpcol = "MarkerName" if "MarkerName" in df else "SNP"
    a1col = "Effect_allele" if "Effect_allele" in df else "A1"
    a2col = "Other_allele" if "Other_allele" in df else "A2"
    pcol = "P-value" if "P-value" in df else "P"

    df.loc[0:499, a1col] = "A"; df.loc[0:499, a2col] = "T"        # ambiguous
    df.loc[500:799, a1col] = "AT"                                  # indel
    df.loc[800:999, "CHR"] = "6"; df.loc[800:999, "BP"] = 28_000_000  # MHC
    df.loc[1000:1099, pcol] = np.nan                               # missing P
    df.loc[1100:1199, pcol] = 0.0                                  # invalid P
    df = pd.concat([df, df.iloc[2000:2300]], ignore_index=True)     # duplicates
    return df.sample(frac=1, random_state=1).reset_index(drop=True)


# --- synthetic LDSC logs ------------------------------------------------------
#
# h2 logs. Two of these are engineered to FAIL the QC gate, by the two
# different mechanisms that CLAUDE.md insists must never be conflated:
#   longsleep  -> Z = 0.012/0.006 = 2.0, intercept fine  -> underpowered
#   shortsleep -> Z = 0.040/0.008 = 5.0, intercept 1.35  -> confounded
# A gate that only ever sees passing traits has not been tested.
#
# (trait, scale, h2, se, intercept, int_se, lambda_gc, mean_chi2, ratio)
H2_ROWS = [
    ("insomnia",   "Liability", 0.0800, 0.0050, 1.0150, 0.0090, 1.0940, 1.1520, 0.0987),
    ("sleepdur",   "Observed",  0.0900, 0.0060, 1.0200, 0.0085, 1.1010, 1.1740, 0.1149),
    ("chronotype", "Liability", 0.1200, 0.0070, 1.0100, 0.0092, 1.1330, 1.2210, 0.0452),
    ("sleepiness", "Observed",  0.0600, 0.0045, 1.0300, 0.0088, 1.0720, 1.1080, 0.2778),
    ("mdd",        "Liability", 0.0900, 0.0055, 1.0250, 0.0095, 1.1120, 1.1900, 0.1316),
    ("t2d",        "Liability", 0.1100, 0.0065, 1.0400, 0.0101, 1.1560, 1.2650, 0.1509),
    ("cad",        "Liability", 0.0700, 0.0050, 1.0350, 0.0098, 1.0980, 1.1620, 0.2160),
    ("longsleep",  "Liability", 0.0120, 0.0060, 1.0080, 0.0087, 1.0110, 1.0190, 0.4211),
    ("shortsleep", "Liability", 0.0400, 0.0080, 1.3500, 0.0140, 1.4020, 1.4800, 0.7292),
]

# rg grid, 4 sleep x 3 disease. rg sweeps a straight arithmetic ramp from
# -0.45 to +0.43 in steps of 0.08 (row-major). This is a gradient, not a
# result: it is instantly recognisable as artificial, while still driving
# both halves of the diverging colorbar.
#
# The z values are chosen so that after BH-FDR across all 12 pairs the star
# annotations come out 4x'***', 2x'**', 2x'*' and 4x blank -- every branch of
# stars() in 06_heatmap.py, including the blank path that a matrix of
# uniformly-significant fake numbers never reaches.
RG_SLEEP = ["chronotype", "insomnia", "sleepdur", "sleepiness"]
RG_DISEASE = ["mdd", "t2d", "cad"]
RG_VALUES = [-0.45, -0.37, -0.29,
             -0.21, -0.13, -0.05,
              0.03,  0.11,  0.19,
              0.27,  0.35,  0.43]
RG_Z = [-6.0, -4.5, -3.1,
        -2.4, -1.2, -0.4,
         0.3,  1.1,  2.2,
         3.4,  5.0,  7.0]

RG_HEADER = ("p1 p2 rg se z p h2_obs h2_obs_se h2_int h2_int_se "
             "gcov_int gcov_int_se")


def write_h2_logs(outdir):
    """One h2_<trait>.log per trait, in the shape 05_collate.py parses."""
    written = []
    for trait, scale, h2, se, icept, icept_se, lam, chi2, ratio in H2_ROWS:
        body = (
            f"{SMOKE_BANNER}\n"
            f"Call: ldsc.py --h2 SYNTHETIC/{trait}.sumstats.gz\n\n"
            f"Total {scale} scale h2: {h2:.4f} ({se:.4f})\n"
            f"Lambda GC: {lam:.4f}\n"
            f"Mean Chi^2: {chi2:.4f}\n"
            f"Intercept: {icept:.4f} ({icept_se:.4f})\n"
            f"Ratio: {ratio:.4f} ({icept_se * 4:.4f})\n"
        )
        path = os.path.join(outdir, f"h2_{trait}.log")
        with open(path, "w") as fh:
            fh.write(body)
        written.append(path)
    return written


def write_rg_logs(outdir):
    """One rg_<sleeptrait>.log per sleep trait, mirroring 04_rg.sh, which
    calls LDSC once per sleep trait against a comma-separated disease list."""
    from scipy.stats import norm

    written = []
    for i, s in enumerate(RG_SLEEP):
        rows = []
        for j, d in enumerate(RG_DISEASE):
            k = i * len(RG_DISEASE) + j
            rg, z = RG_VALUES[k], RG_Z[k]
            se = abs(rg / z)
            p = 2 * norm.sf(abs(z))
            rows.append(
                f"SYNTHETIC/{s}.sumstats.gz SYNTHETIC/{d}.sumstats.gz "
                f"{rg:.4f} {se:.4f} {z:.4f} {p:.4g} "
                f"0.0900 0.0055 1.0250 0.0095 0.0041 0.0060"
            )
        body = (
            f"{SMOKE_BANNER}\n"
            f"Call: ldsc.py --rg SYNTHETIC/{s}.sumstats.gz,...\n\n"
            "Summary of Genetic Correlation Results\n"
            f"{RG_HEADER}\n" + "\n".join(rows) + "\n\n"
            "Analysis finished.\n"
        )
        path = os.path.join(outdir, f"rg_{s}.log")
        with open(path, "w") as fh:
            fh.write(body)
        written.append(path)
    return written


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="data/raw",
                    help="destination for raw sumstats")
    ap.add_argument("--logs", action="store_true",
                    help="write synthetic LDSC h2/rg logs to --logdir")
    ap.add_argument("--logdir", default="results/_smoketest",
                    help="MUST stay separate from results/logs/")
    ap.add_argument("--raw", action="store_true",
                    help="write raw sumstats too when --logs is given")
    a = ap.parse_args()

    if os.path.normpath(a.logdir) == os.path.normpath("results/logs"):
        raise SystemExit(
            "ERROR: refusing to write synthetic logs into results/logs/.\n"
            "       Real and fake LDSC output must never share a directory —\n"
            "       05_collate.py globs the directory and cannot tell them apart."
        )

    if a.logs:
        os.makedirs(a.logdir, exist_ok=True)
        for p in write_h2_logs(a.logdir) + write_rg_logs(a.logdir):
            print(f"wrote {p}")
        print(f"\n{len(H2_ROWS)} h2 logs + {len(RG_SLEEP)} rg logs in {a.logdir}")
        print("Every value in them is fabricated. Next:")
        print(f"  python3 scripts/05_collate.py --mode h2 --logdir {a.logdir} "
              f"--out {a.logdir}/h2_summary.tsv")
        print(f"  python3 scripts/05_collate.py --mode rg --logdir {a.logdir} "
              f"--out {a.logdir}/rg_matrix.tsv")
        print(f"  python3 scripts/06_heatmap.py --rg {a.logdir}/rg_matrix.tsv \\")
        print('      --config config/traits.tsv \\')
        print(f'      --out {a.logdir}/fig2_smoketest.png \\')
        print('      --provenance-label "SYNTHETIC — NOT REAL DATA"')

    if a.raw or not a.logs:
        os.makedirs(a.out, exist_ok=True)
        for trait, style, sepc in [("insomnia", "beta", "\t"), ("mdd", "or", " ")]:
            d = make(style=style)
            f = os.path.join(a.out, f"{trait}.txt.gz")
            d.to_csv(f, sep=sepc, index=False, compression="gzip")
            print(f"wrote {f}  ({len(d):,} rows, style={style})")
